<a href="https://colab.research.google.com/github/Krishnavenia68/assignment/blob/main/SQL_Data_Analysis_on_Film_Locations_Dataset.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import sqlite3

In [ ]:
df = pd.read_csv("Film_Locations_in_San_Francisco.csv")
df.head()

,Title,Release Year,Locations,Fun Facts,Production Company,Distributor,Director,Writer,Actor 1,Actor 2,Actor 3
0,180,2011,Epic Roasthouse (399 Embarcadero),NaN,SPI Cinemas,NaN,Jayendra,"Umarji Anuradha, Jayendra, Aarthi Sriram, & Suba",Siddarth,Nithya Menon,Priya Anand
1,180,2011,Mason & California Streets (Nob Hill),NaN,SPI Cinemas,NaN,Jayendra,"Umarji Anuradha, Jayendra, Aarthi Sriram, & Suba",Siddarth,Nithya Menon,Priya Anand
2,180,2011,Justin Herman Plaza,NaN,SPI Cinemas,NaN,Jayendra,"Umarji Anuradha, Jayendra, Aarthi Sriram, & Suba",Siddarth,Nithya Menon,Priya Anand
3,180,2011,200 block Market Street,NaN,SPI Cinemas,NaN,Jayendra,"Umarji Anuradha, Jayendra, Aarthi Sriram, & Suba",Siddarth,Nithya Menon,Priya Anand
4,180,2011,City Hall,NaN,SPI Cinemas,NaN,Jayendra,"Umarji Anuradha, Jayendra, Aarthi Sriram, & Suba",Siddarth,Nithya Menon,Priya Anand

In [ ]:
df.columns

Index(['Title', 'Release Year', 'Locations', 'Fun Facts', 'Production Company',
       'Distributor', 'Director', 'Writer', 'Actor 1', 'Actor 2', 'Actor 3'],
      dtype='object')

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1586 entries, 0 to 1585
Data columns (total 11 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Title               1586 non-null   object
 1   Release Year        1586 non-null   int64
 2   Locations           1532 non-null   object
 3   Fun Facts           438 non-null    object
 4   Production Company  1584 non-null   object
 5   Distributor         1465 non-null   object
 6   Director            1582 non-null   object
 7   Writer              1563 non-null   object
 8   Actor 1             1558 non-null   object
 9   Actor 2             1463 non-null   object
 10  Actor 3             1084 non-null   object
dtypes: int64(1), object(10)
memory usage: 136.4+ KB

In [ ]:
conn = sqlite3.connect("movies.db")

In [ ]:
df.to_sql("film_locations",conn, if_exists="replace",index=False)

1586

In [ ]:
df.to_sql("film_locations", conn, if_exists="replace", index=False)

1586

In [ ]:
query = """
SELECT name
FROM sqlite_master
WHERE type ='table';
"""
pd.read_sql_query(query,conn)

             name
0  film_locations

In [ ]:
query = """
SELECT *
FROM film_locations;
"""

pd.read_sql_query(query, conn).head()

,Title,Release Year,Locations,Fun Facts,Production Company,Distributor,Director,Writer,Actor 1,Actor 2,Actor 3
0,180,2011,Epic Roasthouse (399 Embarcadero),None,SPI Cinemas,None,Jayendra,"Umarji Anuradha, Jayendra, Aarthi Sriram, & Suba",Siddarth,Nithya Menon,Priya Anand
1,180,2011,Mason & California Streets (Nob Hill),None,SPI Cinemas,None,Jayendra,"Umarji Anuradha, Jayendra, Aarthi Sriram, & Suba",Siddarth,Nithya Menon,Priya Anand
2,180,2011,Justin Herman Plaza,None,SPI Cinemas,None,Jayendra,"Umarji Anuradha, Jayendra, Aarthi Sriram, & Suba",Siddarth,Nithya Menon,Priya Anand
3,180,2011,200 block Market Street,None,SPI Cinemas,None,Jayendra,"Umarji Anuradha, Jayendra, Aarthi Sriram, & Suba",Siddarth,Nithya Menon,Priya Anand
4,180,2011,City Hall,None,SPI Cinemas,None,Jayendra,"Umarji Anuradha, Jayendra, Aarthi Sriram, & Suba",Siddarth,Nithya Menon,Priya Anand

In [ ]:
query = """
SELECT locations,writer
FROM film_locations;
"""
pd.read_sql_query(query,conn).tail()

                                              Locations            Writer
1581                                1801 Laguna at Bush     Norman Foster
1582  Cable Car Signal Box (California Street at Pow...     Norman Foster
1583                                312 Fillmore Street        Vera Blasi
1584                                               None  Bob Carroll, Jr.
1585             SF Chronicle Building (901 Mission St)  James Vanderbilt

In [ ]:
query = """
SELECT "Releaseyear"
FROM film_locations
WHERE"Releaseyear" >2010;
"""
pd.read_sql_query(query,conn)

     "Releaseyear"
0      Releaseyear
1      Releaseyear
2      Releaseyear
3      Releaseyear
4      Releaseyear
...            ...
1581   Releaseyear
1582   Releaseyear
1583   Releaseyear
1584   Releaseyear
1585   Releaseyear

[1586 rows x 1 columns]

In [ ]:
query = """
SELECT Title,"Release year"
FROM film_locations
ORDER BY "Release year"DESc;
"""
pd.read_sql_query(query,conn).head()

                      Title  Release Year
0  Budding Prospects, Pilot          2017
1  Budding Prospects, Pilot          2017
2  Budding Prospects, Pilot          2017
3  Budding Prospects, Pilot          2017
4  Budding Prospects, Pilot          2017

In [ ]:
query ="""
SELECT *
FROM film_locations
LIMIT 10;
"""
pd.read_sql_query(query,conn)

,Title,Release Year,Locations,Fun Facts,Production Company,Distributor,Director,Writer,Actor 1,Actor 2,Actor 3
0,180,2011,Epic Roasthouse (399 Embarcadero),None,SPI Cinemas,None,Jayendra,"Umarji Anuradha, Jayendra, Aarthi Sriram, & Suba",Siddarth,Nithya Menon,Priya Anand
1,180,2011,Mason & California Streets (Nob Hill),None,SPI Cinemas,None,Jayendra,"Umarji Anuradha, Jayendra, Aarthi Sriram, & Suba",Siddarth,Nithya Menon,Priya Anand
2,180,2011,Justin Herman Plaza,None,SPI Cinemas,None,Jayendra,"Umarji Anuradha, Jayendra, Aarthi Sriram, & Suba",Siddarth,Nithya Menon,Priya Anand
3,180,2011,200 block Market Street,None,SPI Cinemas,None,Jayendra,"Umarji Anuradha, Jayendra, Aarthi Sriram, & Suba",Siddarth,Nithya Menon,Priya Anand
4,180,2011,City Hall,None,SPI Cinemas,None,Jayendra,"Umarji Anuradha, Jayendra, Aarthi Sriram, & Suba",Siddarth,Nithya Menon,Priya Anand
5,180,2011,Polk & Larkin Streets,None,SPI Cinemas,None,Jayendra,"Umarji Anuradha, Jayendra, Aarthi Sriram, & Suba",Siddarth,Nithya Menon,Priya Anand
6,180,2011,Randall Museum,None,SPI Cinemas,None,Jayendra,"Umarji Anuradha, Jayendra, Aarthi Sriram, & Suba",Siddarth,Nithya Menon,Priya Anand
7,180,2011,555 Market St.,None,SPI Cinemas,None,Jayendra,"Umarji Anuradha, Jayendra, Aarthi Sriram, & Suba",Siddarth,Nithya Menon,Priya Anand
8,24 Hours on Craigslist,2005,None,None,Yerba Buena Productions,Zealot Pictures,Michael Ferris Gibson,None,Craig Newmark,None,None
9,40 Days and 40 Nights,2002,"The Walden House, Buena Vista Park","Established in 1867, Buena Vista Park is the o...",Miramax Films,Miramax Films,Michael Lehmann,Robert Perez,Josh Hartnett,Shaynnyn Sossamon,None

In [ ]:
query = """
SELECT COUNT(*) AS total_movies
FROM film_locations;
"""

pd.read_sql_query(query, conn)

   total_movies
0          1586

In [ ]:
query = """
SELECT Director,
COUNT(*) AS total_movies
FROM film_locations
GROUP BY Director
ORDER BY total_movies DESC;
"""

pd.read_sql_query(query, conn).head()

         Director  total_movies
0    Andrew Haigh           125
1  Steven Bochcho            58
2  Philip Kaufman            32
3     Woody Allen            31
4  Buddy Van Horn            29

In [ ]:
query = """
SELECT Director,
COUNT(*) AS total_movies
FROM film_locations
GROUP BY Director
HAVING total_movies > 5
ORDER BY total_movies DESC;
"""

pd.read_sql_query(query, conn)

          Director  total_movies
0     Andrew Haigh           125
1   Steven Bochcho            58
2   Philip Kaufman            32
3      Woody Allen            31
4   Buddy Van Horn            29
..             ...           ...
74   Norman Foster             6
75  Marcia Kimpton             6
76       Jon Amiel             6
77     J.J. Abrams             6
78    Herbert Ross             6

[79 rows x 2 columns]

In [ ]:
query = """
SELECT Title, Locations
FROM film_locations
WHERE Locations LIKE '%Bridge%';
"""

pd.read_sql_query(query, conn)

,Title,Locations
0,A View to a Kill,Lefty O' Doul Drawbridge/ 3rd Street Bridge (3...
1,A View to a Kill,Golden Gate Bridge
2,Bicentennial Man,Golden Gate Bridge
3,Boys and Girls,Golden Gate Bridge
4,Bullitt,Bay Bridge
5,Dark Passage,Golden Gate Bridge
6,Dream with the Fishes,Bay Bridge
7,Flower Drum Song,Golden Gate Bridge
8,George of the Jungle,Bay Bridge
9,Golden Gate,Golden Gate Bridge
10,Herbie Rides Again,Golden Gate Bridge
11,Hulk,Golden Gate Bridge
12,Innerspace,Golden Gate Bridge
13,Interview With The Vampire,Golden Gate Bridge
14,It Came From Beneath the Sea,Golden Gate Bridge
15,Jagged Edge,Golden Gate Bridge
16,Looking,Golden Gate Bridge
17,Looking,Bay Bridge
18,Magnum Force,Lefty O' Doul Drawbridge/ 3rd Street Bridge (3...
19,Magnum Force,Golden Gate Bridge
20,Milk,Golden Gate Bridge
21,Mother,Golden Gate Bridge
22,On the Road,Bay Bridge
23,Seven Girlfriends,Golden Gate Bridge
24,Shadow of the Thin Man,Bay Bridge
25,Star Trek IV: The Voyage Home,Golden Gate Bridge
26,Star Trek VI: The Undiscovered Country,Golden Gate Bridge
27,Superman,Golden Gate Bridge
28,Terminator - Genisys,San Francisco - Oakland Bay Bridge
29,The Bridge,Golden Gate Bridge
30,The Caine Mutiny,Golden Gate Bridge
31,The Core,Golden Gate Bridge
32,The Dead Pool,Fremont Street Exit of Bay Bridge
33,The Enforcer,Lefty O' Doul Drawbridge/ 3rd Street Bridge (3...
34,The Game,Bay Bridge
35,The Graduate,Bay Bridge
36,The Love Bug,Golden Gate Bridge
37,The Maltese Falcon,Golden Gate Bridge
38,The Presidio,Golden Gate Bridge
39,Time After Time,Golden Gate Bridge
40,When We Rise,Bay Bridge

In [ ]:
query = """
SELECT *
FROM film_locations
WHERE Director IS NULL;
"""

pd.read_sql_query(query, conn)

,Title,Release Year,Locations,Fun Facts,Production Company,Distributor,Director,Writer,Actor 1,Actor 2,Actor 3
0,Bar Rescue,2016,Fort 1,None,Bongo LLC,Spike,None,None,None,None,None
1,Bar Rescue - Season 4 Ep 18,2015,The Holding Company (now called Patriot House ...,"""Loose Lips Loose Tips""",Bongo LLC,Spike,None,None,None,None,None
2,Bar Rescue - Season 4 Ep 21,2015,"Park 77 (now called The Lister Bar), 77 Cambon...","""Sticky Situation""",Bongo LLC,Spike,None,None,None,None,None
3,Bar Rescue - Season 5 Ep 8,2016,"Sam Jordan's Bar and Grill, 4004 3rd St, San F...","""Gettin' Jigger With It,"" Named after it's fou...",Bongo LLC,Spike,None,None,None,None,None

In [ ]:
query = """
SELECT AVG("Release Year") AS average_year
FROM film_locations;
"""

pd.read_sql_query(query, conn)

   average_year
0   1998.169609

In [ ]:
query = """
SELECT MAX("Release Year") AS latest_movie
FROM film_locations;
"""

pd.read_sql_query(query, conn)

   latest_movie
0          2017

In [ ]:
query = """
SELECT MIN("Release Year") AS oldest_movie
FROM film_locations;
"""

pd.read_sql_query(query, conn)

   oldest_movie
0          1915

In [ ]:
query = """
SELECT Title, Director, "Release Year"
FROM film_locations
WHERE "Release Year" > 2000
AND Director IS NOT NULL;
"""

pd.read_sql_query(query, conn)

            Title       Director  Release Year
0             180       Jayendra          2011
1             180       Jayendra          2011
2             180       Jayendra          2011
3             180       Jayendra          2011
4             180       Jayendra          2011
..            ...            ...           ...
833  When We Rise   Gus Van Sant          2017
834  When We Rise   Gus Van Sant          2017
835  When We Rise   Gus Van Sant          2017
836  When We Rise   Gus Van Sant          2017
837        Zodiac  David Fincher          2007

[838 rows x 3 columns]